/*REALIZALAS SIGUIENTES CONSULTAS EN SQL SERVER:
GENERAR UTILIZANDO INSTRUCCIONES DDL LA TABLA: SERV_CASA.*/
CREATE table SERV_CASA (COD_CASA VARCHAR(10),TIPO_SERV VARCHAR(15),DISTINCT FLOAT);
/*GENERAR UTILIZANDO INSTRUCCIONES DDL: MODIFICAR LA TABLA PROVINCIA Y
AÑADIR EL CAMPO NOMBRE CON SUS PROPIEDADES.*/
UPDATE PROVINCIA   SET
/*GENERAR UTILIZANDO INSTRUCCIONES DDL: MODIFICAR LA DEFINICIÓN DEL CAMPO
MUNICIPIO DE LA TABLA HABITACIÓN PARA QUE CONTEMPLE LA RELACIÓN CON LA
TABLA CASA_RURAL.*/

/*BORRAR LA PROPIEDAD DE VALOR NO NULO DEL CAMPO NOMBRE DE LA TABLA
MUNICIPIO.*/
DELE
/*INSERTAR UN REGISTRO COMPLETO (SIN AÑADIR NULOS) EN LA TABLA CASA_RURAL.
SUBIR UN 1% EL PRECIO DE LA NOCHE DE LAS CASAS UBICADAS EN EL MUNICIPIO DE
LA LAGUNA.*/

/*ELIMINAR LAS CASAS RURALES DE LA OROTAVA QUE TIENEN UN PRECIO POR NOCHE
SUPERIOR A 200 €.*/
PRIMERO LA CONSULTA DESPUES ELIMINAR
/*NOMBRE DEL DUEÑO Y DIRECCIÓN COMPLETA (CON EL NOMBRE DEL MUNICIPIO) DE
TODAS LAS CASAS RURALES DE LA PROVINCIA DE GRAN CANARIA.*/
SELECT
    CASA_RURAL.DUENYOL,
    CASA_RURAL.DIRECCION,
    PROVINCIA.NOMBRE
FROM
    CASA_RURAL
    INNER JOIN MUNICIPIO
    ON CASA_RURAL.MUNICIPIO=MUNICIPIO.CODIGO
    INNER JOIN PROVINCIA
    ON MUNICIPIO.PROVINCIA= PROVINCIA.CODIGO
WHERE
    PROVINCIA.NOMBRE='GRAN CANARIA';
/*NOMBRE DEL DUEÑO DE LAS CASAS QUE TIENEN TV Y WIFI EN TODAS LAS
HABITACIONES.*/
SELECT
    CASA_RURAL.DUENYOL
FROM
    CASA_RURAL
    INNER JOIN HABITACION
    ON CASA_RURAL.CODIGO=HABITACION.COD_CASA;
/*PRECIO MEDIO DE LAS CASAS (ALQUILER COMPLETO) CON BAÑO EN ALGUNA HABITACIÓN
QUE HAYAN SIDO CONSTRUIDAS O REHABILITADAS DESPUÉS DEL AÑO 2016.*/
SELECT
    AVG(CASA_RURAL.PRECIO_EUR)
FROM
    CASA_RURAL
    INNER JOIN HABITACION
    ON CASA_RURAL.CODIGO=HABITACION.COD_CASA
WHERE
    HABITACION.BANYO='s'
    AND CASA_RURAL.FECHA_CONSTRUCCION>'2016'
    OR CASA_RURAL.FECHA_REHABILITACION>'2016';
/*CÓDIGO Y DIRECCIÓN DE LAS CASAS EN LAS QUE HAY AL MENOS 2 HABITACIONES CON
BAÑO Y CABEN COMO MÁXIMO 8 PERSONAS EN ESTAS HABITACIONES.*/

/*MOSTRAR EL CÓDIGO DE LAS CASAS CUYO PRECIO ES SUPERIOR AL 80% DE LAS CASAS
del municipio de Arafo.*
/

/*CÓDIGO DE LAS CASAS CUYA DISTANCIA MEDIA A TODOS LOS SERVICIOS DISPONIBLES
SEA SUPERIOR A 2 KM.*
*/

/*MOSTRAR LAS HABITACIONES CON BAÑOS CUYOS PRECIOS SEAN INFERIORES AL 15% DE
LAS HABITACIONES DENTRO DEL MISMO MUNICIPIO.*
/

/*CÓDIGO Y PRECIO DE LA HABITACIÓN MÁS CARA DE LAS CASAS QUE ESTÁN A MENOS
DE UN KM DE UN SUPERMERCADO.*/

/*CÓDIGO, DIRECCIÓN, TELÉFONO Y EMAIL DE LAS CASAS QUE ESTÉN COMO MUCHO A 1
KM DE UN SUPERMERCADO, UNA FARMACIA Y UN CENTRO DE SALUD.*
/

/*CÓDIGO Y MUNICIPIO DE LA CASA CUYA DISTANCIA AL HOSPITAL MÁS PRÓXIMO ES LA
MÍNIMA DE TODAS LAS CASAS. INDICAR TAMBIÉN ESTA DISTANCIA.*
/

/*SERVICIO MÁS PRÓXIMO Y MÁS ALEJADO JUNTO CON LA DISTANCIA CORRESPONDIENTE
PARA CADA CASA.*
/
