CREATE DABASE COMERCIO;

USE COMERCIO;

CREATE TABLE EMPLEADO (
    ID_EMPLEADO INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    APELLIDO_PATERNA VARCHAR(50),
    APELLIDO_MATERNO VARCHA(50)
);

CREATE TABLE ARTICULO (
    ID_ARTICULO INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    PRECIO DECIMAL(10, 2),
);

CREATE TABLE VENTA (
    CLAVE INT PRIMARY KEY,
    FECHA DATE,
    ID_EMPLEADO INT,
    ID_ATICULO INT,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO),
    FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO)
);

INSERT INTO TABLE EMPLEADO (
    ID_EMPLEADO,
    NOMBRE,
    APELLIDO_PATERNA,
    APELLIDO_MATERNO
) VALUE(
    1,
    'Juan',
    'Pérez',
    'Garcia'
),
(
    2,
    'Maria',
    'Garcia',
    'lópez'
),
(
    3,
    'Carlos',
    'Lopez'
);

INSERT INTO TABLE ARTICULO VALUES (
    1,
    'laptop',
    800.00
),
(
    2,
    'smartphone',
    600.00
),
(
    3,
    'table',
    400.00
);

INSERT INTO TABLE VENTAS VALUES(
    101,
    '2024-04-01',
    1,
    1
),
(
    102,
    '2024-04-02',
    2.2
),
(
    103,
    '2024-04-03',
    3,
    3
);

CREATE VIEW TICKET AS (
    SELECT V.CLAVE,
    V.FECHA,
    A.NOMBRE AS PRODUCTO,
    A.PRECIO,
    CONCAT(E.NOMBRE, ' ', E.APELLIDO_PATERNA)AS EMPLEADO
     FROM VENTAS V INNER JOIN EMPLEADO E ON V.ID_EMPLEADO =E.ID_ARTICULO
      INNER JOIN ARTICULO A ON A.ID_ARTICULO = V.ID_ARTICULO
);

SELECT
    *
FROM
    TICKET;

SELECT
    CLAVE,
    Precio AS TOTAL
FROM
    TICKET
GROUP BY
    CLAVE ,precio;
 drop VIEW TICKET;

    CREATE VIEW TICKET(primero,segundo,tercero,cuarto,quinto) AS (
    SELECT V.CLAVE,
    V.FECHA,
    A.NOMBRE AS PRODUCTO,
    A.PRECIO,
    CONCAT(E.NOMBRE, ' ', E.APELLIDO_PATERNA)AS EMPLEADO FROM VENTAS V INNER JOIN EMPLEADO E ON V.ID_EMPLEADO =E.ID_ARTICULO INNER JOIN ARTICULO A ON A.ID_ARTICULO = V.ID_ARTICULO
);

